
const state = { cfg:null, token:null, role:'viewer' };
let ALLOWLIST = ['wykiesautomation@gmail.com'];
let GSI_CLIENT_ID = null;

function $(s, root=document){ return root.querySelector(s); }
function $all(s, root=document){ return Array.from(root.querySelectorAll(s)); }
function show(el){ el.classList.remove('hidden'); } function hide(el){ el.classList.add('hidden'); }

async function loadConfig(){ state.cfg = await fetch('../config.json').then(r=>r.json()); ALLOWLIST = state.cfg.adminAllowEmails||ALLOWLIST; GSI_CLIENT_ID = state.cfg.gsiClientId||null; return state.cfg; }
function saveSession(){ localStorage.setItem('wykies_admin_session', JSON.stringify({token:state.token, role:state.role, t:Date.now()})); }
function loadSession(){ try{ const s = JSON.parse(localStorage.getItem('wykies_admin_session')); if(s){ state.token=s.token; state.role=s.role||'viewer'; } }catch(e){} }
function clearSession(){ localStorage.removeItem('wykies_admin_session'); state.token=null; state.role='viewer'; }
function applyRoleUI(){ const badge=$('#roleBadge'); if(badge) badge.textContent=`Role: ${state.role}`; $all('[data-role="admin-only"]').forEach(x=>{ if(state.role==='admin'){ x.removeAttribute('disabled'); x.style.display='inline-block'; } else { x.setAttribute('disabled','true'); x.style.display='none'; } }); }

function toQuery(obj){ const p=new URLSearchParams(); Object.entries(obj).forEach(([k,v])=>{ if(v!==undefined && v!==null) p.append(k, String(v)); }); return p.toString(); }
async function api(action, body=null){ const base=`${state.cfg.scriptUrl}?action=${encodeURIComponent(action)}`; if(body){ if(state.token && !('token' in body)) body.token=state.token; const r=await fetch(base,{method:'POST', headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'}, body:toQuery(body)}); return r.json(); } else { const u=new URL(base); if(state.token) u.searchParams.set('token', state.token); const r=await fetch(u.toString()); return r.json(); } }

function initGSI(){ if(!window.google || !GSI_CLIENT_ID) return; google.accounts.id.initialize({ client_id:GSI_CLIENT_ID, callback:onGoogleCredential, ux_mode:'popup', auto_select:false }); google.accounts.id.renderButton($('#gsiContainer'), { theme:'filled_black', size:'large', text:'continue_with', shape:'pill' }); }
async function onGoogleCredential(resp){ $('#loginError').hidden = true; try{ const res = await api('gsilogin', { credential: resp.credential }); if(!res.ok) throw new Error('not allowed'); state.token = res.token; state.role = res.role||'admin'; saveSession(); hide($('#loginView')); show($('#appView')); applyRoleUI(); await loadProducts(); await loadOrders(); await loadPayments(); await loadLogs(); }catch(err){ const el=$('#loginError'); el.textContent='Google sign‑in failed or not allowed.'; el.hidden=false; }}

async function onLogin(e){ e.preventDefault(); $('#loginError').hidden=true; const passphrase=$('#passphrase').value.trim(); try{ const res=await api('login',{passphrase}); if(!res.ok) throw new Error('bad'); state.token=res.token; state.role=res.role||'admin'; saveSession(); hide($('#loginView')); show($('#appView')); applyRoleUI(); await loadProducts(); await loadOrders(); await loadPayments(); await loadLogs(); }catch(err){ const el=$('#loginError'); el.textContent='Login failed. Check passphrase.'; el.hidden=false; }}

async function loadProducts(){ $('#statusMsg').textContent='Loading products…'; try{ const rows=await api('listProducts'); const tb=$('#productsTable tbody'); tb.innerHTML=''; (rows||[]).forEach(r=>{ const tr=document.createElement('tr'); tr.innerHTML=`<td>${r.sku}</td><td>${r.name}</td><td>R${Number(r.price).toLocaleString()}</td><td>${r.active?'Yes':'No'}</td><td><button class='btn btn-secondary' data-do='edit'>Edit</button> <button class='btn btn-outline' data-do='toggle'>${r.active?'Disable':'Enable'}</button></td>`; tr.querySelector('[data-do="edit"]').addEventListener('click',()=>editProduct(r)); tr.querySelector('[data-do="toggle"]').addEventListener('click',()=>toggleProduct(r)); tb.appendChild(tr); }); $('#statusMsg').textContent=''; }catch(e){ $('#statusMsg').textContent='Failed to load products.'; }}
function promptEdit(field, init){ const v=prompt(`Enter ${field}:`, init==null?'':String(init)); return v==null? null : v; }
async function editProduct(r){ if(state.role!=='admin'){ alert('Admin only'); return; } const name=promptEdit('name', r.name); if(name===null) return; const price=promptEdit('price', r.price); if(price===null) return; const imageUrl=promptEdit('imageUrl', r.imageUrl||''); if(imageUrl===null) return; const trialUrl=promptEdit('trialUrl', r.trialUrl||''); if(trialUrl===null) return; const docUrl=promptEdit('docUrl', r.docUrl||''); if(docUrl===null) return; const buyUrl=promptEdit('buyUrl', r.buyUrl||''); if(buyUrl===null) return; try{ await api('updateProduct',{sku:r.sku, name, price:Number(price), imageUrl, trialUrl, docUrl, buyUrl}); await loadProducts(); }catch(e){ alert('Update failed'); }}
async function toggleProduct(r){ if(state.role!=='admin'){ alert('Admin only'); return; } try{ await api('updateProduct',{sku:r.sku, active:!r.active}); await loadProducts(); }catch(e){ alert('Update failed'); }}
async function addProduct(){ if(state.role!=='admin'){ alert('Admin only'); return; } const sku=promptEdit('SKU','WA-XX'); if(sku===null) return; const name=promptEdit('name','New Product'); if(name===null) return; const price=promptEdit('price (incl VAT)',0); if(price===null) return; const imageUrl=promptEdit('imageUrl',''); if(imageUrl===null) return; const trialUrl=promptEdit('trialUrl',''); if(trialUrl===null) return; const docUrl=promptEdit('docUrl',''); if(docUrl===null) return; const buyUrl=promptEdit('buyUrl',''); if(buyUrl===null) return; try{ await api('addProduct',{sku, name, price:Number(price), imageUrl, trialUrl, docUrl, buyUrl, active:true}); await loadProducts(); }catch(e){ alert('Add failed'); }}

async function loadOrders(){ try{ const rows=await api('listPayments'); const tb=$('#ordersTable tbody'); tb.innerHTML=''; (rows||[]).forEach(r=>{ const tr=document.createElement('tr'); tr.innerHTML=`<td>${r.timestamp||''}</td><td>${r.invoiceNo||r.orderId||''}</td><td>${r.email||''}</td><td>${r.sku||''}</td><td>R${Number(r.totalInclVAT||0).toLocaleString()}</td><td><button class='btn btn-secondary' data-do='resend'>Resend Invoice</button></td>`; tr.querySelector('[data-do="resend"]').addEventListener('click',()=>resendInvoice(r)); tb.appendChild(tr); }); }catch(e){} }
async function loadPayments(){ try{ const rows=await api('listPayments'); const tb=$('#paymentsTable tbody'); tb.innerHTML=''; (rows||[]).forEach(r=>{ const tr=document.createElement('tr'); tr.innerHTML=`<td>${r.timestamp||''}</td><td>${r.invoiceNo||''}</td><td>${r.email||''}</td><td>${r.sku||''}</td><td>R${Number(r.totalInclVAT||0).toLocaleString()}</td>`; tb.appendChild(tr); }); }catch(e){} }
async function loadLogs(){ try{ const rows=await api('listLogs'); const tb=$('#logsTable tbody'); tb.innerHTML=''; (rows||[]).forEach(r=>{ const tr=document.createElement('tr'); tr.innerHTML=`<td>${r.timestamp}</td><td>${r.actor}</td><td>${r.action}</td><td>${r.entity||''}</td><td>${r.result||''}</td>`; tb.appendChild(tr); }); }catch(e){} }

async function savePage(){ if(state.role!=='admin'){ alert('Admin only'); return; } const slug=$('#pageSlug').value.trim(); const title=$('#pageTitle').value.trim(); const body=$('#pageBody').value; try{ const res=await api('savePage',{slug,title,body}); $('#pagesStatus').textContent = res && res.ok ? 'Saved.' : 'Save failed.'; }catch(e){ $('#pagesStatus').textContent='Save failed.'; }}
function previewPage(){ const body=$('#pageBody').value; const w=window.open('', '_blank'); w.document.write('<pre>'+body.replace(/[&<>]/g, s=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[s]))+'</pre>'); }

async function resendInvoice(row){ if(state.role!=='admin'){ alert('Admin only'); return; } try{ const res=await api('resendInvoice',{invoiceNo:row.invoiceNo, email:row.email, sku:row.sku, total:row.totalInclVAT}); alert(res && res.ok ? 'Invoice resent.' : 'Failed to resend.'); }catch(e){ alert('Failed to resend.'); }}

function initTabs(){ $all('.tab').forEach(btn=>btn.addEventListener('click',()=>{ $all('.tab').forEach(b=>b.classList.remove('active')); btn.classList.add('active'); const name=btn.dataset.tab; $all('.tabpanel').forEach(p=>p.classList.add('hidden')); document.querySelector(`#tab-${name}`).classList.remove('hidden'); })); }

async function main(){ await loadConfig(); initTabs(); loadSession(); applyRoleUI(); $('#loginForm').addEventListener('submit', onLogin); $('#btnSignOut').addEventListener('click', ()=>{ clearSession(); location.reload(); }); $('#btnAddProduct').addEventListener('click', addProduct); $('#btnSavePage').addEventListener('click', savePage); $('#btnPreviewPage').addEventListener('click', previewPage); initGSI(); if(state.token){ try{ const res=await api('session'); if(res.ok){ hide($('#loginView')); show($('#appView')); state.role=res.role||state.role; applyRoleUI(); await loadProducts(); await loadOrders(); await loadPayments(); await loadLogs(); } else { clearSession(); } }catch(e){} } }

document.addEventListener('DOMContentLoaded', main);
